### ISSUE TITLE
兼用模式下，页面弹出“网页对话框”，点击对话框其中的链接，跳转到 IE 浏览器去了。

### ISSUE THREAD

**Issue by onia** [yxl/Fire-IE#145]
兼用模式下，页面弹出“网页对话框”，点击其中的链接，跳转到 IE 浏览器去了。

点击对话框里面的链接怎么会跳转到 IE 浏览器了呢？

有没有办法强制在新 tab 打开所有页面（包括对话框）呢？

测试版本: 0.4.1

**Comment by patwonder** [comment]
有测试链接么？

**Comment by onia** [comment]
@patwonder 暂时没有，稍后我去查查。

**Comment by onia** [comment]
一个测试例子：http://share.weiyun.com/9a3a3be9462844174f712e4b4e699ff6 。

大概就是 test.htm 中 js 调用 window.showModalDialog() 打开 a.htm，a.htm 中又调用 window.open() 打开 b.htm，b.htm 就跑到 IE 去了。

**Comment by patwonder** [comment]
这是IE自己的问题吧。。网站代码写成这样也不容易啊。

**Comment by onia** [comment]
@patwonder 呃，有什么解决办法吗？

**Comment by patwonder** [comment]
没啥办法。。对话框里的请求 Fire IE 管不了。
Issue 先关了。
