### ISSUE TITLE
中信银行规则优化

### ISSUE THREAD

**Issue by renyouguo** [yxl/Fire-IE#147]
目前规则是全局的：||ecitic.com^
事实上完全不需要。
如信用卡快捷服务Firefox下完全正常：
https://creditcard.ecitic.com/citiccard/cppnew/entry.do?func=entryebank&ebankPage=mainpage

需用IE的是网上银行：
https://e.bank.ecitic.com/perbank5/signInCredit.do

所以规则应该可以修改为：
|https://e.bank.ecitic.com

**Comment by patwonder** [comment]
网上银行域名都在```e.bank.ecitic.com```么？我这里不好测试。。

**Comment by renyouguo** [comment]
是的，全在该域名下。
提交的另外一个无锡农商行也是如此。

**Comment by patwonder** [comment]
已更新：https://github.com/yxl/fireie.org/commit/3f569535eec9fdfdf9a29c32b2d82085d78b16bf
