### ISSUE TITLE
规则提交：证券从业人员资格考试网上报名

### ISSUE THREAD

**Issue by renyouguo** [yxl/Fire-IE#148]
建议规则：||sac.ata.net.cn^
地址：http://sac.ata.net.cn/SGZJ05REG/

反复提示要求用IE，如果无视，注册页面会出现部分下拉菜单无法正常显示的问题。

**Comment by patwonder** [comment]
已添加：https://github.com/yxl/fireie.org/commit/3f569535eec9fdfdf9a29c32b2d82085d78b16bf
