### ISSUE TITLE
规则：12306

### ISSUE THREAD

**Issue by ivysrono** [yxl/Fire-IE#150]
现在12306.cn还有哪里是必须IE的？
买了这么久的票，感觉Firefox从头到尾无障碍啊。

**Comment by yxl** [comment]
网银支付部分网站无法在Firefox下完成。

**Comment by renyouguo** [comment]
很蛋疼的试了一下，从头到尾Firefox模式，很顺利的跳转进入了建行、招行、农行和支付宝的付款页面啊。哪里有问题？
