### ISSUE TITLE
IE模式下不兼容 FireGestures 用其他浏览器打开的手势

### ISSUE THREAD

**Issue by renyouguo** [yxl/Fire-IE#151]
win8.1 x64 IE11
Firefox 35.0.1
FireGestures 1.8.7
fireIE 0.4.3/0.4.4b
测试地址：https://e.bank.ecitic.com/perbank5/signInCredit.do
兼容模式下滑动手势用IE打开，会询问「要允许这个网站打开你计算机上的应用吗？」
取消，则打开如下网址：
chrome://fireie/content/container.xhtml?url=https://e.bank.ecitic.com/perbank5/signInCredit.do
如果调用Chrome打开则会是个单纯的空白页。

脚本如下：
用IE打开：
const IE_PATH = "C:\\Program Files\\Internet Explorer\\iexplore.exe";

var file = Cc["@mozilla.org/file/local;1"].createInstance(Ci.nsILocalFile);
file.initWithPath(IE_PATH);
if (!file.exists()) {
  alert("File does not exist: " + IE_PATH);
  return;
}
var process  = Cc["@mozilla.org/process/util;1"].createInstance(Ci.nsIProcess);
try {
  var args = [window.content.location.href];
  process.init(file);
  process.run(false, args, args.length);
}
catch (ex) {
  alert("Failed to execute: " + IE_PATH);
}

用Chrome打开：
const Chrome_PATH = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe";

var file = Cc["@mozilla.org/file/local;1"].createInstance(Ci.nsILocalFile);
file.initWithPath(Chrome_PATH);
if (!file.exists()) {
  alert("File does not exist: " + Chrome_PATH);
  return;
}
var process  = Cc["@mozilla.org/process/util;1"].createInstance(Ci.nsIProcess);
try {
  var args = [window.content.location.href];
  process.init(file);
  process.run(false, args, args.length);
}
catch (ex) {
  alert("Failed to execute: " + Chrome_PATH);
}

**Comment by patwonder** [comment]
把脚本中的
```javascript
window.content.location.href
```
改为
```javascript
(typeof(gFireIE) !== "undefined") ? gFireIE.getURL() : window.content.location.href
```

**Comment by renyouguo** [comment]
谢谢
