### ISSUE TITLE
能否添加IE6模式？

### ISSUE THREAD

**Issue by renyouguo** [yxl/Fire-IE#154]
部分网站——主要是政府内网——烂到IE7+就要开兼容模式，实在没办法。

**Comment by patwonder** [comment]
IE兼容模式通过注册表项FEATURE_BROWSER_EMULATION控制，详见http://msdn.microsoft.com/zh-CN/library/ee330730%28v=vs.85%29.aspx#browser_emulation

由于只有IE8以上版本支持FEATURE_BROWSER_EMULATION，且最低只能指定IE7兼容模式，因此无法支持IE6兼容模式，除非直接使用IE6。
