### ISSUE TITLE
能否实现对不同网站调用不同模式？

### ISSUE THREAD

**Issue by renyouguo** [yxl/Fire-IE#155]
有的网站只能IE7（证券从业人员资格考报名）
也有只能IE6的（某些机关内网）
还有只能IE8的（还是某些机关内网）

能通过规则来实现么？

**Comment by patwonder** [comment]
不能实现，原因和#154类似，FEATURE_BROWSER_EMULATION只在启动时读取一次，改变兼容模式需要重启浏览器/插件进程。
