### ISSUE TITLE
支持uBlock

### ISSUE THREAD

**Issue by ivysrono** [yxl/Fire-IE#157]
µBlock :: Firefox 附加组件
https://addons.mozilla.org/zh-CN/firefox/addon/ublock/

已正式提交至 amo ，且效果上佳。
请求支持。

**Comment by patwonder** [comment]
由于µBlock架构与ABP有很大的不同，且目前还在开发阶段，无法预计是否会有API方面的变动，短期内解雇IE不会考虑支持µBlock。待其相对稳定后，会考虑支持。

**Comment by xxy171070** [comment]
由于ublock版本分裂，所以现在出现了两个版本的ublock，一个是ublock，另一个是ublock origin。
ublock版本分裂原因：https://github.com/gorhill/uBlock
ublock的安装地址：https://addons.mozilla.org/zh-CN/firefox/addon/ublock/
而ublock origin安装地址：https://addons.mozilla.org/zh-CN/firefox/addon/ublock-origin/
希望Fire-IE能早点支持这两个版本的ublock。
