### ISSUE TITLE
建议对规则进行 x86 与 x64 的区分

### ISSUE THREAD

**Issue by ivysrono** [yxl/Fire-IE#160]
Firefox x64 已经进入beta通道。
有 Chrome x64 铺垫在前，可见网上支付系统支持x64浏览器遥遥无期。
除了浦发可以彻底伪装为Linux以实现免除插件外，其他网银统统等走IE模式。
这显然与x86冲突严重。
能否实现两套规则，然后安装时自动判断呢？

**Comment by patwonder** [comment]
你想要什么样的效果？不支持 Firefox 32 位的网站同样也不会支持 Firefox 64 位。

**Comment by renyouguo** [comment]
但现在的问题是很多支持32位的网站不支持64位，如招商银行网银，工商银行网银等等。
基本上国内的插件都没有x64的。

**Comment by patwonder** [comment]
但是对规则进行 x86 与 x64 的区分能解决你说的问题么？同样都是不支持，即使未来支持了，也很有可能是优先支持 x64 IE 的。

**Comment by renyouguo** [comment]
不好意思，我想当然的以为Firefox x64 调用IE就好，没想到调用的 x64 IE 还是不支持。
那不能实现保持调用 x86 IE？不能的话的确没意义。

**Comment by patwonder** [comment]
目前的 in-process 插件模式下，插件与 Firefox 运行在同一进程中，64 位 Firefox 只能调用 64 位的 IE，因为 Windows 不允许同一个进程混合 32 位和 64 位的代码。
0.4.5b 版本默认启用 out-of-process plugin，插件运行在 plugin-container.exe 进程中。但是 64 位 Firefox 默认带的是 64 位的 plugin-container.exe，同样只能调用 64 位 IE。

[Bug 595053](https://bugzilla.mozilla.org/show_bug.cgi?id=595053) 提到了 OOPP 模式下 64 位 Firefox 支持 32 位插件的问题，但该 bug 目前状态是 WONTFIX，可能永远都不会实现。

@xunxun1982 的 pcxfirefox 倒是有个版本支持加载 32 位插件的。

**Comment by renyouguo** [comment]
是的，但停留在Firefox15，且pcx不愿意继续维护这个功能。

**Comment by xunxun1982** [comment]
我原来看过一篇文章似乎可以通过COM来让x64进程访问x86进程
