### ISSUE TITLE
能否支持LastPass？

### ISSUE THREAD

**Issue by renyouguo** [yxl/Fire-IE#162]
最实用的扩展之一，现在真心不记得密码，在 IE mode 下真麻烦。

**Comment by patwonder** [comment]
理论上可行，实际情况是实现太麻烦，由于 LastPass 不能识别 IE 引擎的 DOM 树，要支持 LastPass 工作量堪比重新写一个针对 IE 引擎的 LastPass（ABP 支持同理），且不容易维护。所以我们暂时没有支持 LastPass 的计划。
