### ISSUE TITLE
白名单网站自动切换回 Firefox mode 丢失 cookie？

### ISSUE THREAD

**Issue by ivysrono** [yxl/Fire-IE#163]
添加了自定义白名单规则：@@||ebank.spdb.com.cn^
证券从业人员报名网站 http://sac.ata.net.cn/SGZJ05REG/ 之前已加入 IE 自动切换列表。
注册成功后在 http://sacbook.ata.net.cn:7980/ZQSS/Bank/BookList.aspx 随便找本书购买，环迅支付付费，选择浦发银行， 一路跳转都是 IE mode，但最后跳转到浦发 https://ebank.spdb.com.cn/payment/main 的时候会提示错误：

交易失败
十分抱歉，您提交的交易未成功。
com.csii.pe.core.PeException MessageCode: system.undefined_transaction Args:

**Comment by patwonder** [comment]
跳转回 Firefox 引擎时，如果是 POST 操作，解雇IE 不会把 post 的数据传输到 Firefox 引擎。

 

From: bounces+848413-8174-patwonder=vip.163.com@sgmail.github.com [mailto:bounces+848413-8174-patwonder=vip.163.com@sgmail.github.com] On Behalf Of renyouguo
Sent: Saturday, March 14, 2015 1:50 PM
To: yxl/Fire-IE
Subject: [Fire-IE] 白名单网站自动切换回 Firefox mode 丢失 cookie？ (#163)

 

添加了自定义白名单规则：@@||ebank.spdb.com.cn^
证券从业人员报名网站 http://sac.ata.net.cn/SGZJ05REG/ 之前已加入 IE 自动切花你列表。
注册成功后在 http://sacbook.ata.net.cn:7980/ZQSS/Bank/BookList.aspx 随便找本书购买，环迅支付付费，选择浦发银行， 一路跳转都是 IE mode，但最后跳转到浦发 https://ebank.spdb.com.cn/payment/main 的时候会提示错误：

交易失败
十分抱歉，您提交的交易未成功。
com.csii.pe.core.PeException MessageCode: system.undefined_transaction Args:
