### ISSUE TITLE
webex page returns error after auto switch in Firefox 38.0a2 64 bit (dev edition)

### ISSUE THREAD

**Issue by kmr2319** [yxl/Fire-IE#165]
Attempting to start or Join a WebEx session in Firefox 38.0a2 x64 fails (really a WebEx problem, but attempting to workaround it with Fire IE). When using Auto Switch for *.webex.com, and a URL that looks like this: https://xxxxxxx.webex.com/xxxxxxx/j.php?J=99999999, the IE engine is started, the page redirects a few times (normal), but ultimately returns an error on the webex page:
"Java is not working.  
To have the best experience joining meetings, Java must be installed on your computer and enabled in your browser and the Java Control Panel. Install and enable Java, restart your browser if needed, and then join the meeting again. "

![image](https://cloud.githubusercontent.com/assets/11653089/6833256/f834f5c2-d301-11e4-8dce-32b78013880a.png)

If I then right click on the FireIE icon and choose "Open this page in IE Browser", the page opens successfully and loads the WebEx session properly.

**Comment by patwonder** [comment]
Do you have x64 Java installed on your computer? In Firefox x64, Fire IE loads the x64 Internet Explorer engine rather than the x86 version.

**Comment by kmr2319** [comment]
I did not have Java x64 installed. I installed it and it started to work...

The funny thing about this is, with only the 32 bit Java installed, opening webex URLs with the 64 Bit IE worked just fine... Very odd... 

If you can't think of anything in the FireIE code that might explain any of this, then feel free to close out this report.

Thanks!

**Comment by patwonder** [comment]
Unless you turn [Enhanced Protected Mode](https://msdn.microsoft.com/en-us/library/ie/dn265025%28v=vs.85%29.aspx) on, IE browser runs its tabs in 32-bit processes regardless of the "bitness" of its UI process. You can verify this by opening the task manager and see if there are both 64-bit and 32-bit versions of iexplore.exe running.

**Comment by kmr2319** [comment]
Great info! Thanks for looking into this. Feel free to close this one out.

Here's some additional info on [EPM] (http://blogs.msdn.com/b/ie/archive/2012/03/14/enhanced-protected-mode.aspx)

Looks like there's another setting "Enable 64 bit processes for Enhanced Protection Mode" that might also need to be enabled to make IE "truly" 64 bit.

Thanks again!

**Comment by patwonder** [comment]
BTW, we're thinking of the possibility to load 32-bit IE engine in 64-bit Firefox (through a 32-bit plugin-container.exe). This would allow some IE plugins that only have 32-bit versions to work under Fire IE. It would solve your issue as well without the need of a 64-bit Java installation.
