### ISSUE TITLE
Feature Request: Allow auto switch rules to open in IE Browser (rather than an IE Tab)

### ISSUE THREAD

**Issue by kmr2319** [yxl/Fire-IE#166]
Would like the ability for Auto Switch sites to open the IE Browser automatically (rather than an IE Tab within Firefox).

Ideally, the option should be set on the rule group (if enabled, all sites within that rule group would open in the IE Browser - all other rule groups would open in an IE Tab by default). However a global option would be sufficient as well.

**Comment by patwonder** [comment]
I think [IE View](https://addons.mozilla.org/en-us/firefox/addon/ie-view/) already implements this.

Fire IE is supposed to focus on the embedded IE engine, thus I don't think we will implement this.

**Comment by kmr2319** [comment]
IE View hasn't been updated in over 2 years (like basically every other "Open in IE" plugin out there expect for Fire IE). Where as this is an active project.

I'd be willing to bet that IE View doesn't work in Firefox 38 x64. I won't bother testing it at all since the reviews of that plugin are filled with complaints about Ads and Spyware that are packaged with it.

In addition, it would be a nice to have feature within Fire IE to avoid having 2 plugins with very similar functionality. Fire IE is also more advanced as it provides an extremely robust regex/pattern matching capabilities for selecting targeted sites - IE View uses very basic string matching.

Those are just some thoughts - but I do understand the want/need to sticking to "core" functionality. Thanks for reviewing this!
