### ISSUE TITLE
FireIE如何调试ActiveX插件？

### ISSUE THREAD

**Issue by onia** [yxl/Fire-IE#168]
请教一个问题，FireIE如何调试ActiveX插件？遇到某些插件，Firefox崩溃自动退出。

**Comment by patwonder** [comment]
关掉崩溃报告器：
![](https://cloud.githubusercontent.com/assets/1505712/7552959/943edd3e-f706-11e4-882e-d4793f884dad.png)

或者启动时直接附加调试器，崩溃报告器也不会起作用。

**Comment by onia** [comment]
@patwonder 可以分析出是什么 ActiveX 插件导致崩溃的么？

**Comment by patwonder** [comment]
Fire IE 不会去记录这些东西。附加一个调试器，崩溃的时候看一下调用栈，一般会指出哪个DLL出问题的。

**Comment by onia** [comment]
没查出具体原因，先关闭 issue 了。
