### ISSUE TITLE
怎么办把最新版的 OOPP 模式切换到之前的模式？

### ISSUE THREAD

**Issue by onia** [yxl/Fire-IE#172]
如题，有时候浏览器放着不动，等一会插件自动崩溃了，OOPP 模式可以通过 config 临时关闭吗？

**Comment by weideng** [comment]
可以, 添加dom.ipc.plugins.PLUGINNAME.enabled设置为false

**Comment by onia** [comment]
@weideng 貌似不行，怎么把 Fireie 切换到以前的模式？

**Comment by patwonder** [comment]
`dom.ipc.plugins.enabled.npfireie32.dll` -> **`false`**

**Comment by onia** [comment]
@patwonder 成了，谢谢。
