### ISSUE TITLE
FireIE DLL plugin not successfully loaded in Firefox 41 x64.

### ISSUE THREAD

**Issue by kaymer327** [yxl/Fire-IE#173]
![fireie](https://cloud.githubusercontent.com/assets/11653089/9237154/606aaa46-4117-11e5-81a0-4fbe08678b4c.png)

The above error occurs when launching Firefox 41 Beta 1 x64 on Windows 10. This did not occur with Firefox 40 x64 on Windows 10 (same system).

**Comment by patwonder** [comment]
The win64 version of Firefox 41 disallows any plugin other than Adobe Flash. See https://bugzilla.mozilla.org/show_bug.cgi?id=1165981 for details.

Unfortunately, there's nothing we can do on our side. The workaround is to switch to the 32bit version of Firefox 41.

**Comment by HRLake** [comment]
I get the exact same error notification using the 32 bit version of Firefox 40.0 on Windows 7 Home Premium 64 bit. Tried uninstalling, rebooting, reinstalling, restarting, rebooting - all to no avail.

**Comment by patwonder** [comment]
@HRLake That's odd. Do you see "Fire IE DLL" listed in the page "about:plugins"?

**Comment by ben00460** [comment]
我也有相同的問題...
FF 40 32BIT+WIN7 64BIT
https://goo.gl/baLpQl
https://goo.gl/Sw8GJD

**Comment by patwonder** [comment]
@ben00460 I can't open the links. Could you upload them here?

**Comment by ben00460** [comment]
![2015-08-19 17 05 28](https://cloud.githubusercontent.com/assets/13866855/9356254/1b7eaa54-46b2-11e5-82a8-b563b5f461c0.png)
![2015-08-19 17 05 29](https://cloud.githubusercontent.com/assets/13866855/9356255/1b8022f8-46b2-11e5-9774-566aced457aa.PNG)

**Comment by patwonder** [comment]
@HRLake @ben00460 Sorry guys. I'm closing this issue because OP's problem has been resolved (won't fix). Your problems seem different from OP's, so please open another issue and we'll discuss there.

Closing this issue as "Won't Fix".

**Comment by HRLake** [comment]
Hello!

Sorry to take so long to reply.

The problem seems to have resolved itself.

Today I downloaded/installed FireIE 0.4.5.2 and all went well and I no longer get the error message.

Yes I do now see “Fire IE DLL” listed in about:plugins. However I never did check to find out if this was true back when I had the error message.

Anyway – all is well now. And hopefully will stay this way. I DO like your addon.

Thanks,

Henry Lake

**Comment by kaymer327** [comment]
@HRLake, is this still with the 32 bit version of Firefox? FireIE 0.4.5.2 and Firefox 41b4 x64 still receive the error (as expected per @patwonder).

**Comment by patwonder** [comment]
@kaymer327 Things are not likely to change for the official x64 version. If you absolutely need to run x64 Firefox, I'd suggest you use a third-party build like [pcxfirefox](http://sourceforge.net/projects/pcxfirefox/) (the author @xunxun1982 said he would consider removing the restriction on usable plugins for pcxfirefox 41 x64).

**Comment by xunxun1982** [comment]
@patwonder I built it: https://sourceforge.net/projects/pcxfirefox/files/Release/Firefox/41.x/41.0/x64/sse2/

**Comment by patwonder** [comment]
@xunxun1982 Thank you!
