### ISSUE TITLE
Plugin loading crash in Mozilla Firefox 64 nightly build (waterfox)

### ISSUE THREAD

**Issue by Ant0nski** [yxl/Fire-IE#176]
Hello,
I cannot use your plugin on one of mine machines, probably because it runs Firefox 64 nightly build (Waterfox). 
There is a message following FF restart, that "Fire IE plugin is not loaded..." and so on.
I could attach a screenshot, but would you tell me whether your plugin is expected to work with FF64 at all?

Thanks in advance,
Anton

**Comment by patwonder** [comment]
I'm sorry for the issues you are experiencing.

Fire IE needs a plugin (Fire IE DLL) to load the Internet Explorer browsing engine. Unfortunately, Mozilla has decided to [pull the plug and stop supporting any kind of plugin other than Adobe Flash](https://bugzilla.mozilla.org/show_bug.cgi?id=1165981) in Firefox x64 builds.

The only workaround, as for now, is to switch to a 32-bit build.

**Comment by Ant0nski** [comment]
Oh, I'm sorry to hear that.
Unfortunately, switching to FF x32 is not an option at the moment.
I hope that you will have some smart idea for an workaround.
Thank you.








 >-------- Оригинално писмо --------

 >От: Yifan Wu notifications@github.com

 >Относно: Re: [Fire-IE] Plugin loading crash in Mozilla Firefox 64 nightly
 build (waterfox) (#176)

 >До: yxl/Fire-IE  

 >Изпратено на: 08.10.2015 16:19



 
 
  
I'm sorry for the issues you are experiencing.  
  
Fire IE needs a plugin (Fire IE DLL) to load the Internet Explorer browsing engine. Unfortunately, Mozilla has decided to  pull the plug and stop supporting any kind of plugin other than Adobe Flash  in Firefox x64 builds.  
  
The only workaround, as for now, is to switch to a 32-bit build.

**Comment by DFlannery** [comment]
Maybe 64bit users should try Waterfox www.waterfoxproject.org ... I am using release 40.0.3 and it still has plugin support.

**Comment by Ant0nski** [comment]
Thank you for suggestion, I tried Waterfox stable and it still works with plugins indeed.
