### ISSUE TITLE
Switching to IE brocken with Firefox 44.0

### ISSUE THREAD

**Issue by marefundo** [yxl/Fire-IE#184]
With new Firefox 44.0 switching to IE does not work any more. Whenever Fire-IE 0.4.5.3 switches to IE, the url changes to just "http:///" and message "This page can’t be displayed" is shown. Problem was't there with Firefox 43.

**Comment by patwonder** [comment]
Fixed in version [0.4.6](https://github.com/yxl/Fire-IE/releases/tag/0.4.6)
