### ISSUE TITLE
0.4.6 和 Firefox 44/44.0.1 不兼容

### ISSUE THREAD

**Issue by asbai** [yxl/Fire-IE#186]
在 Firefox 44 和 44.0.1 上均会出现 plugin-container.exe 无限重启问题——进程被不断杀死和重启：
![fireie](https://cloud.githubusercontent.com/assets/5937547/12911212/b329daf0-cf4b-11e5-8f43-458be4c56996.gif)
![04](https://cloud.githubusercontent.com/assets/5937547/12911214/bd6dc800-cf4b-11e5-91ed-110e4dcd43e1.png)

**Comment by asbai** [comment]
Firefox 32bit version，MSW 2k3

**Comment by patwonder** [comment]
可能是 VS2015 引入的 magic statics 不兼容 NT5.1 所致：https://connect.microsoft.com/VisualStudio/feedback/details/1789709/visual-c-2015-runtime-broken-on-windows-server-2003-c-11-magic-statics

编译时禁用 magic statics (/Zc:threadSafeInit-) 即可解决。

**Comment by asbai** [comment]
我不是自行编译的，直接安装的官方版，addons.mozilla.org 上更新了么？
PS：2k3 的 kernel version 是 NT 5.2 ，问题应该类似？

**Comment by patwonder** [comment]
还没更新，再等等。。

**Comment by patwonder** [comment]
https://addons.mozilla.org/en-US/firefox/addon/fire-ie/versions/0.4.6.1
目前只有未签名版，签名的要再等几天。

**Comment by asbai** [comment]
好的，多谢 :-)
